apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Chart.Name }}-cleaner
  namespace: {{ .Values.global.namespace }}
  labels:
    app: {{ .Chart.Name }}-cleaner
  annotations:
    checksum/config: {{ include (print $.Template.BasePath "/configmap-cleaner.yaml") . | sha256sum }}

spec:
  replicas: {{ .Values.cleaner.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}-cleaner
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}-cleaner
    spec:
      serviceAccountName: {{ .Chart.Name }}-sa # RBAC
      containers:
        - name: cleaner
          image: "{{ .Values.cleaner.image.repository }}:{{ .Values.cleaner.image.tag }}"
          imagePullPolicy: {{ .Values.cleaner.image.pullPolicy }}

          # ── 環境變數注入 ────────────────────────────────
          envFrom:
            - configMapRef:
                name: {{ .Chart.Name }}-cleaner-cm
          {{- if .Values.cleaner.secret.enabled }}
            - secretRef:
                name: {{ .Values.cleaner.secret.name }}
          {{- end }}

          # ── 資源限制 ────────────────────────────────────
          resources:
            {{- toYaml .Values.cleaner.resources | nindent 12 }}
