global:
  namespace: ns-sep-stg
  imagePullSecrets:
    - name: ghcr-secret

quotas:
  systems:
    crawler:
      cpu_request: "100m"
      memory_request: "128Mi"
      cpu_limit: "250m"
      memory_limit: "256Mi"

engine:
  replicas: 1
  port: 8080
  service:
    type: ClusterIP
  image:
    repository: ghcr.io/jefflin0225/kubernetes-serverless/sep-engine
    tag: latest               # ← deploy.sh 執行時用 --set 覆蓋為 sha-xxx
    pullPolicy: IfNotPresent
  resource:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

cleaner:
  replicas: 1
  image:
    repository: ghcr.io/jefflin0225/kubernetes-serverless/sep-cleaner
    tag: latest               # ← deploy.sh 執行時用 --set 覆蓋為 sha-xxx
    pullPolicy: IfNotPresent
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"